steps:

- name: 'gcr.io/cross-xlayers/ngcontainer'
  entrypoint: 'npm'
  args: ['install']

- name: 'gcr.io/cross-xlayers/ngcontainer'
  entrypoint: 'npm'
  args: ['run', 'test:ci']

- name: 'gcr.io/cross-xlayers/ngcontainer'
  entrypoint: 'npm'
  args: ['run', 'build', '--', '--output-path', 'dist/html']
  env:
    - 'BUILD_ID=$BUILD_ID'

# Build snapshot images and push them to Cloud Registry

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/xlayers:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/xlayers:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/xlayers:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/xlayers:latest']

# Copy the content of dist directory to the Persistent Volume

- name: 'gcr.io/cloud-builders/kubectl'
  args: 
    - 'cp'
    - './dist/html'
    - 'nginx-ingress-nginx-0:/usr/share/nginx/html'

  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

# # Set permissions so NGINX server has access to the newly uploaded html directory

- name: 'gcr.io/cloud-builders/kubectl'
  args: 
    - 'exec'
    - 'nginx-ingress-nginx-0'
    - '--'
    - 'chmod'
    - '-R'
    - 'a+r'
    - '/usr/share/nginx/html'

  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'

# Patch a new Ingress ressource for the build $SHORT_SHA

- name: 'gcr.io/cross-xlayers/ngcontainer'
  entrypoint: 'sh'
  args: 
    - '-c'
    - |
        perl -pe "s/SHORT_SHA/$SHORT_SHA/g" scripts/cloudbuild/xlayers.template.yaml > xlayers.$SHORT_SHA.yaml

# # Apply a new Ingress ressource for the build $SHORT_SHA

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f' 
    - 'xlayers.$SHORT_SHA.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=xlayers-staging'

images:
  - 'gcr.io/$PROJECT_ID/xlayers:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/xlayers:latest'